# These are supported funding model platforms

github: jc5
patreon: JC5
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=thegrumpydictator%40gmail.com&item_name=Development&currency_code=EUR&source=url
